export const allProperties = [
  "designation",
  "shortDescription",
  "longDescription",
  "reasonOfQuitting",
  "isActive",
  "userId",
  "company",
  "responsibilities",
  "achievements",
  "tags",
  "mode",
  "shift",
  "startDate",
  "endDate",
  "location",
];
export const validate = [
  "designation",
  "shortDescription",
  "longDescription",
  "reasonOfQuitting",
  "isActive",
  "userId",
  "company",
];
export const otherProperties = [
  "responsibilities",
  "achievements",
  "tags",
  "mode",
  "shift",
  "startDate",
  "endDate",
  "location",
];
