export const allProperties = [
  "title",
  "shortDescription",
  "longDescription",
  "experience",
  "isDegree",
  "isActive",
  "shortTitle",
  "institution",
  "achievements",
  "tags",
  "startDate",
  "endDate",
  "location",
];
export const validate = [
  "name",
  "email",
  "dob",
  "address",
  "phone",
  "designation",
  "intro",
  "image",
  "linkedIn",
  "facebook",
  "instagram",
  "twitter",
  "github",
  "resume",
  "userId",
];
export const otherProperties = ["hobbies", "skills", "tags", "id"];
